name: documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: install dependencies
        run: |
          ls
          pip install .[docs]
      - uses: actions/checkout@v3
      - name: build html
        run: |
          git checkout -b gh-pages
          pip install .
          cd ./docs
          make html
          cd ../
          mv ./docs/build/html/ ../docs/
          git rm -rf '*'
          cp -r ../docs/ ./
      - name: deploy
        env:
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add -f docs
          git commit --allow-empty -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push -f origin HEAD
